logging:
  file:
    path: E://project//logback
server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: stage-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 10
    max-active: 20
    max-idle: 8
    max-wait: 10000
    min-idle: 8
    password: 123456
    url: jdbc:mysql://localhost/user?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
  data:
    mongodb:
      host: localhost # mongodb的连接地址
      port: 27017 # mongodb的连接端口号
      database: demo-port # mongodb的连接的数据库
  redis:
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
    host: 127.0.0.1
    port: 63790
  profiles:
    include: business,persistence,common
